### ISSUE TITLE
php error on "show tags" action

### ISSUE THREAD

**Issue by orthagh** [TECLIB/formcreator#101]
( ! ) Fatal error: Call to a member function getTags() on a non-object path/to/glpi/inc/ notificationtemplatetranslation.class.php on line 331

    Call Stack
    #  Time  Memory   Function Location
    1  0.0002   241656   {main}( )   ../notification.tags.php:0
    2  0.1329   8841848  NotificationTemplateTranslation::showAvailableTags( ) ../notification.tags.php:42

**Comment by neeftarah** [comment]
not present in last release version.
