### ISSUE TITLE
Ticket (sans validation) non créé avec FormCreator 0.85-1.2.3 et GLPI 0.85.4

### ISSUE THREAD

**Issue by CHCI74** [TECLIB/formcreator#106]
Bonjour,
Lors l'utilisation d'un formulaire, le programme indique "Le formulaire a été sauvegardé avec succès !" mais le ticket correspondant n'est pas créé dans la base.
Si je demande une validation (champ : validation requise ?), le ticket se crée bien après action du valideur.
Je viens de migrer de GLPI  0.84.7 et Form Creator ancienne version 1.8.1. vers les versions FormCreator 0.85-1.2.3 et GLPI 0.85.4
Faut-il un paramétrage spécifique pour autoriser automatiquement la création de ticket ?
Merci de votre collaboration.

**Comment by LNAQUAO** [comment]
Bonjour,

(Version GLPI : 0.85.4, version FormCreator : 0.85-1.2.4). Voici le souci : 
1) le demandeur crée un formulaire avec validation requise. Il obtient le message : " le formulaire a été sauvegardé avec succès "
2) le formulaire est envoyé automatiquement au validateur
3) le validateur accepte les données du formulaire. Après avoir cliqué sur le bouton " Accepter " et avoir saisi un commentaire, le message suivant s'affiche en rouge "Demandeur est obligatoire ", puis en dessous : " le formulaire a été sauvegardé avec succès !". Je ne comprend pas le message affiché en rouge car dans la liste des formulaires, le nom du demandeur s'affiche bien !
4) A la suite de la validation : AUCUN ticket n'est crée.

Pourriez-vous me dire d'où vient le problème ???
Pourquoi aucun ticket n'est crée après validation par le validateur ?

Merci
