### ISSUE TITLE
preg_replace() is depreciated

### ISSUE THREAD

**Issue by Stormrage74** [TECLIB/formcreator#109]
hello (bonjour),

(GLPI 0.84.2 - FormCreator 2.1.4)

i expected some bugs (more precisely warnings messages), since i install the new version of this plugin ( a very good plugin :) ), about the depreciated function. Can i manually update it to preg_replace_callback() and what are the changes of the function content ?

Addendum: before i use 5.3.13 php and on my new server i use 5.5.9. 

thanks,
best regards,

Stormrage

**Comment by neeftarah** [comment]
Hi,

preg_replace is not use in formcreator.
And even if it is widely used in GLPI, only the "/e" modifier is deprecated (which should not be used in GLPI). However, GLPI introduce a little bug in their modifier : they use "/entities_id" without escape it. Maybe just escape this should remove the warning ("\/entities_id");

With PHP 5.5+ < PHP 7, you will just have a warning but all still work well.
With PHP 7, you will still have a warning and the "/e" modifier will won't work.

You can see all the documentation on the PHP manual : http://php.net/manual/en/function.preg-replace.php

So their is nothing to do in Formcreator, but I will see with GLPI core developers to fix that.

best regards,
Jérémy
