### ISSUE TITLE
Category of ticket

### ISSUE THREAD

**Issue by StaineRs** [TECLIB/formcreator#114]
Hello, old version of the plugin i could change the category of the ticket by the plugin.
I Just installed new version and when I tried to choose ticket category and is not there. I have lot of rules linked with ticket category... How can I set ticket category now?

**Comment by orthagh** [comment]
Hello.  
You can set the category in the selected ticket template of your form target. 
A "predefined fields" tab is available.

Formcreator use the ticket template (mostly predefined fields) at the creation of target ticket.

Regards.

**Comment by StaineRs** [comment]
I got it, but how can I change the name of this template? how can I edit
these templates?
For example:
I have a form with ticket category = Computer
The name of this template is: Template Formcreator 10
why instead of appear COMPUTER I have to choose TEMPLATE FORMCREATOR 10?
If is possible, how can I edit the category?

Thanks a lot

On Thu, Jul 16, 2015 at 10:25 AM, Alexandre Delaunay <
notifications@github.com> wrote:

> Hello.
>
> You can set the category in the selected ticket template of your form
> target.
> A "predefined fields" tab is available.
>
> Formcreator use the ticket template (mostly predefined fields) at the
> creation of target ticket.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TECLIB/formcreator/issues/114#issuecomment-121954794>.
>



-- 
Dimas Carvalho
Graduando em Engenharia Mecânica - UNIFACS
A Geradora - Setor de Engenharia de Manutenção - ENGEMAN
Salvador - Bahia
Currículo - http://lattes.cnpq.br/0038447692276963 ( Em Construção )
"Há 3 tipos de pessoas: as que sabem contar e as que não sabem."

**Comment by orthagh** [comment]
Go to your tickets list page (in glpi not formcreator), click on the "plus" icon with red background : 

![Uploading Capture du 2015-07-16 15:53:16.png…]()

After that, you must be in ticket templates page where you can edit default template or add new templates.

**Comment by StaineRs** [comment]
I got it !!!!
Thanks a lot
