### ISSUE TITLE
Question de type LDAP impossible à créer

### ISSUE THREAD

**Issue by neeftarah** [TECLIB/formcreator#117]
Dans la création d'une question (exemple le nom), dans le choix d'un champ de type LDAP, nous n'avons pas pu conserver la configuration de serveur LDAP déclaré dans le serveur GLPI.
Nous sélectionnons le type LDAP, puis le serveur déclaré apparait et nous le sélectionnons dans la liste, nous choisissons l'attribut voulut.
Après enregistrement de la question, le serveur LDAP n'est pas conservé et il est donc impossible de requêter le serveur lors de la saisie dans le formulaire.

**Comment by AdAugustaPerAngusta** [comment]
ma version de glpi est la 0.85.4, ma version du plugin est la : 0.90-1.2.5
mais la création d'une question de type LDAP est impossible.
La validation de la création ne se fait pas et la page du formulaire bloque.
Merci de votre aide.
