### ISSUE TITLE
Add type question "Validation" //  Ajouter question de type "Validation"

### ISSUE THREAD

**Issue by matth974** [TECLIB/formcreator#36]
(french)
L'idée étant de pouvoir historiser la demande initiale (matérialisée par l'enregistrement d'un ticket) et de conserver dans l'historique du ticket le choix de l'approbateur (accepté ou refusé).

**Comment by orthagh** [comment]
Nous avons, dans la nouvelle version 0.85-1.2, ajouté une nouvelle option dans les destinations du formulaire, qui permet d'indiquer si un suivi sera ajouté au ticket généré.
Ce suivi contenant le choix et le commentaire de l'approbateur.

Je ne comprend pas le titre de votre issue par contre sa description semble correspondre à cette nouvelle fonctionnalité.

Pouvez-vous tester cette nouvelle version et nous faire un retour ?

Merci d'avance.

**Comment by matth974** [comment]
Bonjour,

Je vous remercie pour ce retour, et m'excuse si ma demande ne parait pas claire. Je ne pourrais pas tester cette version dans l'immédiat, car notre structure utilise pour le moment la version 0.84 de GLPI. Il nous faudrait donc prévoir d'effectuer une montée de version du logiciel, avant de pouvoir tester la nouvelle version du plug in.

Toute fois, je vais tenter de repréciser ma demande pour être sûr que nous parlons de la même chose:

Sur les versions 0.84.2-0 et 0.84.2-1.3 de FormCreator, nous avions remarqué qu'il était possible de demander "validation" à quelqu'un lors de la soumission d'un formulaire.

Sauf que tant que l'approbateur ne répond pas le ticket n'est pas généré.
Il en est de même s'il refuse le formulaire.
Par contre, s'il accepte le ticket est généré.

De même, il semble que la demande de validation ne soit pas tracée dans le ticket créé.

Or, nous aurions souhaité que le formulaire soit enregistré sous forme de tickets quelque soit le statut de l'approbation (en attente, validée ou refusé) et que la demande de validation soit visible dans l'onglet "validation" du ticket ainsi généré.

Pour information, dans une version très ancienne du module formcreator (1-8-1) , il existait la possibilité d'ajouter une question de type "validation" au formulaire.La demande de validation était alors placée dans l'onglet de même nom, mais il y avait un bug sur cette fonctionnalité (la liste des approbateurs n'était pas initialisée:  http://www.glpi-project.org/forum/viewtopic.php?id=34403).

Bien cordialement.

**Comment by orthagh** [comment]
Bonjour, merci de votre retour qui effectivement clarifie un peu le besoin.

Effectivement dans la version actuelle nous avons voulu que la demande de validation soit complètement un préalable (activable ou non) à la création d'un ticket.

Cela permet de faire en série, une validation hiérarchique et une validation technique.
Cette seconde étant permise par la validation classique de GLPI.

Vous pouvez toujours utiliser la validation classique (visible dans l'onglet du ticket) et les règles métier pour les tickets peuvent vous permettre d'automatiser l'envoi de la demande de validation technique.

Nous avons conscience que la validation de "formulaires" peux paraître externe à l'assistance mais c'est clairement le but recherché. Afin de faciliter la lecture tu ticket, nous avons, comme indiqué plus haut, dans la dernière version du plugin, ajouté un suivi avec le commentaire du valideur.

Il reste toutefois le problème que vous mentionnez, à savoir que si un valideur ne valide pas, aucun ticket n'est jamais généré. Il y a sur cette espace une "issue" qui propose une solution élégante à ce problème : #32 .
Une action automatique se chargerait de relancer les valideurs qui n'aurait pas répondu.

Espérant que ces explications vous conviennent.

**Comment by matth974** [comment]
Bonjour,

Merci pour toutes ces précisions qui me permettent effectivement de mieux comprendre votre point de vue.

La présente issue peut donc être clôturée.

Cordialement.

**Comment by orthagh** [comment]
Merci de votre retour.
N'hésitez pas à nous remonter tout problèmes ou suggestions
