### ISSUE TITLE
Add feature to disable email notification to requester

### ISSUE THREAD

**Issue by dethegeek** [TECLIB/formcreator#37]
When a change has been recorded to the ticket, the requester may receive an email notification. Add an option to disable notifications to requesters, an other to disable notifications to observers and an third one for technicians.

**Comment by neeftarah** [comment]
Hi,

A new feature have been develop that can answer to your needs.
The commit e682e6f add the possibility to define actors for a ticket and to specify if he should receive email notification or not.

By default, form requester is still added to the ticket requester with notifications enabled and so for the validator as an observer, but you can delete the default settings and set the actors you want without notification.

This feature have been developped for GLPI 0.85 and will be included in 0.85-1.2 release.
