### ISSUE TITLE
Show field condition issue

### ISSUE THREAD

**Issue by J-n-s** [TECLIB/formcreator#39]
To reproduce, make this form :
Question1 - Radios - Values "1", "2"
Question2 - Select - Show only if Question1=2 - Values "A", "B", "Other"
Question3 - Text - Show only if Question2=Other

Bug on this form :
1- Select value "2" at Question1
2- Select value "Other" at Question2 (Question3 appears => ok)
3- Select value "1" at Question1 => Question3 does not disappear !

Regards, 
Jonas

**Comment by neeftarah** [comment]
Fixed by refactoring (in 0.85)
