### ISSUE TITLE
Possibilté de cloner un formulaire

### ISSUE THREAD

**Issue by flegastelois** [TECLIB/formcreator#49]
Fonctionnalité qui permet de "cloner" un formulaire existant vers un nouveau formulaire.
Afin d'accélérer la création de formulaires qui se ressemblent.
Le nouveau formulaire récupère toutes les infos de l'ancien : 
* actif = NON par défaut
* on demande le nouveau titre en pré-remplissant par ex : "Copie - Ancien nom"
* on récupère questions/sections/cibles/destinations...

**Comment by orthagh** [comment]
je up cette demande, indispensable pour client actuel et couvert dans le projet.
