### ISSUE TITLE
Formulaire accepté : Accepté ne s'affiche pas

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/formcreator#51]
En cas de formulaire à valider, puis refusé, lorsque son auteur ouvre le formulaire, en haut, sous l'entête du formulaire s'affiche 'Refusé' (en rouge)
Mais s'il s'agit d'un formulaire accepté, alors il ne s'affiche qu'un petit carré vert.

De même, si c'est le valideur qui ouvre un formulaire qu'il a refusé, il ne s'affiche rien du tout.

**Comment by neeftarah** [comment]
'Refusé' (en rouge) s'affiche car le commentaire de refus est : "Refusé"
Le "petit carré vert" s'affiche car le commentaire de validation est vide. (non obligatoire pour la validation)

=> Amélioration : Il faudrait rajouter un message par défaut ("Formulaire validé") lorsque le commentaire est vide.

Le valideur ainsi que tous les autres utilisateurs devrais voir les messages d'acceptation ou de refus
=> bug à corriger
