### ISSUE TITLE
intégration des balises de réponses / questions dans le titre du ticket

### ISSUE THREAD

**Issue by orthagh** [TECLIB/formcreator#58]
Est ce possible ?    

Actuellement, les balises ne sont remplacées que dans la description du ticket.

**Comment by neeftarah** [comment]
C'est normalement possible et sur l'un des formulaire que je vient de tester, les balises sont bien parsé dans le titre (réponse aux questions uniquement, pas FULL_FORM).

**Comment by neeftarah** [comment]
Je confirme également pour les balises de questions.
ex : ##question_59## et ##answer_59## sont bien remplacés

**Comment by orthagh** [comment]
Effectivement erreur de ma part.
J'avais mis une balise d'une réponse à une question supprimée.

Ca marche bien comme prévu
