### ISSUE TITLE
Champ "Zone de texte" tronqué à 255 caractères. Possibilité d'augmenter cette limite?

### ISSUE THREAD

**Issue by matth974** [TECLIB/formcreator#60]
Le champ "Zone de texte" ne prend en compte que les 255 premiers caractères à la validation du formulaire. Est-ce volontaire? Est-ce possible d'augmenter cette limite, car la saisie d'un texte long est tronqué.

- Autre idée, à défaut:

Avoir le choix entre plusieurs type de champs Zone de texte:
> Zone de texte court (255 caractères)
> Zone de texte long (500 caractères)
> Zone de texte très long ( 1000 caractères)

Merci

**Comment by neeftarah** [comment]
Corrigée en 0.85-1.1 et 0.84-2.1.3
