### ISSUE TITLE
Cannot add a question

### ISSUE THREAD

**Issue by wawax** [TECLIB/formcreator#61]
Using formcreator tag 0.85-1.1RC1

I cannot add a question, I've got the following error in debug mode : 

Fatal error: Can't use method return value in write context in /opt/www/html/glpi/plugins/formcreator/inc/fields/checkboxes-field.class.php on line 11 

PHP version is 5.3.3 : 
[root@glpi formcreator]# php -v
PHP 5.3.3 (cli) (built: Oct 30 2014 20:12:53) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

Explanation here : 
http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

The bug might happens on PHP < 5.5

**Comment by orthagh** [comment]
Also, please don't use php empty function ! 
empty is true when ckecked var is false or not set. 

For testing emptiness of an array (the array is set, but has no keys/values), use : 

if (count($array) > 0) {
   ...
}

**Comment by neeftarah** [comment]
@wawax I look at this as sone as possible (and need to install PHP 5.3 on my computer)

@orthagh the empty function also return true on an empty array (set but with no value) as with "0", 0, NULL, 0.0 values or unset variables. There should be no problem unless you use the "0" value (and only this value) in your checkbox field
