### ISSUE TITLE
Langue de l'email de demande de validation

### ISSUE THREAD

**Issue by babalou** [TECLIB/formcreator#69]
Bonjour,

J'utilise GLPI 0.84.7 et le plugin formcreator 2.1.3. J'ai créé un formulaire associé à la langue "Français", avec une demande de validation. L'email envoyé au validateur est en toujours anglais au lieu d'être en français. Comment puis-je résoudre ce problème ?

Très cordialement et encore bravo pour ce plugin !

Cyril

**Comment by neeftarah** [comment]
Bonjour,
Formcreator utilise le système de notification standard de GLPI.
Par défaut, seule la traduction Anglaise des "modèles de notification" (donc des contenus des e-mail) est enregistrée à l'installation.

Avez-vous saisie une traduction Française dans les modèles de notification ?

Si ce n'est pas le cas, il suffit d'aller sur la page Configuration > Notifications > Modèles de notification, rechercher les modèles ayant pour type "Formulaire saisi" et une fois sur la fiche détaillée, ajoutez une traduction "Française" ou modifiez la traduction par défaut.

**Comment by babalou** [comment]
Bonjour,

Merci beaucoup pour votre réactivité. J'ai suivi votre procédure et j'ai pu configurer la version française du modèle intitulé "Un formulaire est en attente de validation" qui est utilisé pour la demande de validation.

Cordialement.
