### ISSUE TITLE
Redirection sur un formulaire Form Creator après login.

### ISSUE THREAD

**Issue by KevinSupertramp** [TECLIB/formcreator#71]
Bonjour,

Premièrement je tenais à vous remercier pour ce plugin qui m'est très utile ! Je me demandais s'il était possible de "forcer la redirection" vers un formulaire Form Creator après l'authentification de l'utilisateur ?

Merci d'avance,
Kevin

**Comment by neeftarah** [comment]
Bonjour,

En version GLPI 0.85, si vous transmettez l'URL du formulaire, l'utilisateur sera automatiquement redirigé vers la page du formulaire.

    ex: http://votre_serveur/glpi/plugins/formcreator/front/showform.php?id=XXX

Cordidalement,
Jérémy

**Comment by KevinSupertramp** [comment]
Bonjour,

Merci beaucoup et désolé pour le temps de réponse.
Il faut du coup que je fasse la mise à jour GLPI.

Bonne journée,
Kevin
