### ISSUE TITLE
Erreur de caractères spéciaux

### ISSUE THREAD

**Issue by kaioisdead** [TECLIB/formcreator#76]
Bonjour !

Un problème de caractères spéciaux (accents) apparait lors de la création d'un ticket par formcreator, les réponses (table answer) n'apparaissent pas correctement dans la description et le titre du ticket.
Ceci depuis la mise à jour 0.85-1.0 vers 0.85-1.2

- Version : 0.85-1.0 : Pas de soucis constatés
- Version : 0.85-1.1 : problème constaté
- Version : 0.85-1.2 : problème constaté

Merci pour votre excellent travail,
![glpi_createform_error](https://cloud.githubusercontent.com/assets/11302259/6472518/6aad331e-c1f3-11e4-9a0b-9c2bc8164bf8.jpg)

**Comment by neeftarah** [comment]
Bonjour,

Je suis désolé mais je n'arrive pas à reproduire votre bug.
Des modifications ont été faites sur ces versions aux niveaux des encodages mais ne devrais pas poser de problèmes surtout depuis la version 1.2.

Toutefois, si vous avez des questions, des valeurs par défaut ou tout type de valeurs enregistrées au niveau des questions, je vous invite à réenregistrer chacune de vos question contenant des caractères spéciaux ou accentués afin de ré-encodé ces valeurs en base de données.

Si le problème persiste, pouvez-vous m'indiquer votre navigateur, OS, etc. ainsi que la configuration de vos formulaires et question posant problème ?

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
Bonjour,

Pouvez-vous me confirmer que vous avez toujours le problème avec la dernière version et les instructions ci-dessus ?

Merci de votre retour.

Cordialement,
Jérémy

**Comment by kaioisdead** [comment]
Bonsoir,

Désolé pour ma réponse tardive, je rééssaye demain et vous tiendrai au courant avec la toute dernière version de formcreator.

Je constate une différence avec la version GLPI 0.85.2 + formcreator 0.85-1.2 entre windows et linux.

C'est à dire : 
- Pas de soucis sur Linux = Ubuntu + apache + MySQL
- Problèmes décrits plus haut avec Win Server 2008R2 + IIS + MySQL

Je vous remercie grandement pour votre soutient et vos réponses.
Bien à vous,
Mickael

**Comment by wawax** [comment]
Same error yesterday on linux with the latest release (1.2.1)

**Comment by kaioisdead** [comment]
Bonjour,
Je viens de tester une maj de formcreator 1.2.1, effectivement le problème persiste. J'ai aussi essayé la version master de ce matin, j'ai le problème également. J'ai donc fais un retour en arrière en 1.0 et plus de souci.

Merci de votre aide,
Très sincèrement,
Mickael

**Comment by neeftarah** [comment]
Bonjour,

Je suis désolé mais je n'arrive pas à reproduire ce bug.

Tests effectués sous GLPI 0.85.3 avec Formcreator 0.85-1.2.1 :
- Chrome / Ubuntu
- Firefox / Ubuntu
- IE 9 / Windows

Merci de me donné plus d'informations (déjà demandé).
Navigateur, OS, etc. ainsi que la configuration de vos formulaires et question posant problème ?

Votre base de données MySQL à-t-elle bien été créée en "unicode / UTF-8" ?
Quel est votre version de PHP ?


Merci de votre retour,
Cordialement,
Jérémy

**Comment by kaioisdead** [comment]
Bonjour,

Oui désolé, voici plus de détails, je viens de tester avec les dernières versions possibles : 
Clients : 
- IE11 / Win8.1
- Firefox 36 / Win8.1
- IE11 / Win7
- Firefox 36 / Win7

Serveur : 
- GLPI 0.85.3 + FormCreator 1.2.1
- Win2008R2
- IIS 7.5
- PHP 5.3.6
- MySQL 5.5.13 - BDD en utf8_general_ci

![2015-03-18_14-49-11](https://cloud.githubusercontent.com/assets/11302259/6710320/1407815c-cd80-11e4-9d9e-0a848941c228.jpg)

![2015-03-18_14-59-50](https://cloud.githubusercontent.com/assets/11302259/6710259/9c2e686c-cd7f-11e4-9698-8c59d9b51a91.jpg)
![2015-03-18_15-00-46](https://cloud.githubusercontent.com/assets/11302259/6710260/9c32812c-cd7f-11e4-82c1-67cb7ef5d0ab.jpg)

**Comment by neeftarah** [comment]
Merci de ces infos !
Je soupçonne fortement PHP 5.3 d'en être la cause. Je fait des tests en ce sens et voit si je peut remplacer les fonctions problématiques.

**Comment by neeftarah** [comment]
Le problème était bien due à PHP 5.3 et la fonction htmlentities qui ne supporte pas les chaînes encodées en UTF-8 sur cette version de PHP.
Le problème sera corrigé sur la prochaine version de formcreator (0.85-1.2.2).

Merci de votre aide pour débusquer ce bug.
