### ISSUE TITLE
Not display form list.

### ISSUE THREAD

**Issue by consolko** [TECLIB/formcreator#77]
Hello! Does not display a forms list in "Simplified interface" of user profile, only show in "Full interface". How fix this? :)
![simpl_profile](https://cloud.githubusercontent.com/assets/9745539/6570786/5a72cd74-c711-11e4-9afe-806a15c38e58.png)
![full_profile](https://cloud.githubusercontent.com/assets/9745539/6570787/5a75b746-c711-11e4-9632-a8e48e318110.png)

**Comment by neeftarah** [comment]
It was a regression introduced in version 0.85-1.2. The fix will be included in next release 0.85-1.2.2 probably next week.
