### ISSUE TITLE
Error : Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5'

### ISSUE THREAD

**Issue by wawax** [TECLIB/formcreator#78]
The following error occured : 
2015-03-10 17:16:25 [2@glpiapp1]
  *** PHP Notice(8): Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5'
  Backtrace :
  plugins/formcreator/inc/question.class.php:458     
  plugins/formcreator/front/question.form.php:17     PluginFormcreatorQuestion->updateConditions()

**Comment by neeftarah** [comment]
This bug is specific to PHP <= 5.3.
This line of code was added during developpment and was removed immediately. It should not appear  in no tag or release.
