### ISSUE TITLE
Changer la forme de sélection des valideurs (dans la config)

### ISSUE THREAD

**Issue by flegastelois** [TECLIB/formcreator#79]
Bonjour,

En conception de formulaire, dans le cas où il y a plusieurs valideurs possibles pour un formulaire, il faut sélectionner dans la liste déroulante les différentes valeurs.

Dans certains cas, ou par exemple il faut sélectionner 120 valideurs … cette sélection est longue, fastidieuse et vraiment pas ergonomique.

Egalement, en cas d’ajout d’un valideur (par la suite), il faut re-sélectionner l’ensemble des valideurs …

Est-il possible d’envisager l’évolution de cette fonction, en affichant une multi-liste par exemple ?

++

**Comment by orthagh** [comment]
cf : 

http://paramquery.com/select
http://davidstutz.github.io/bootstrap-multiselect/ (dépendance sur bootstrap)
