### ISSUE TITLE
Date d'échéance bloquée à 1

### ISSUE THREAD

**Issue by osfrance** [TECLIB/formcreator#86]
Bonjour,
J'ai trouvé un Bug  dans la destination du Ticket au niveau de la date d'échéance calculée à partir de la date de création du ticket : 
Le nombre reste toujurs à 1 après validation quelque soit la fréquence choisie (Heure, minutes, jours ...)

Merci d'avance
-Oliv'

**Comment by osfrance** [comment]
Après Vérification, la date est bien calculée sur le ticket, c'est juste l'affichage du champs de la date qui reste à 1.

**Comment by neeftarah** [comment]
Bonjour,
Il y avait effectivement un petit problème d'initialisation de la liste déroulante.
Ce problème est réglé et la correction sera incluse dans la prochaine version 0.85-1.2.4.

Merci de votre retour,
Jérémy
