### ISSUE TITLE
Migration GLPI et formulaires

### ISSUE THREAD

**Issue by matth974** [TECLIB/formcreator#89]
Bonjour,

Nous utilisons actuellement Form Creator v.0.84-2.1.3 sous GLPI 0.84.3.
Nous avons d'ores et déjà créer quelques formulaires avec cette version, et nous nous interrogeons sur le devenir de ces formulaires dans le cadre d'une éventuelle migration de GLPI.
Nous craignons que les formulaires ainsi mis en place, soient "détruits", lors d'une montée de version.

Existe t-il une procédure particulière détaillant les précautions à prendre pour migrer proprement les formulaires existants?

En vous remerciant par avance.

Cordialement.

**Comment by neeftarah** [comment]
Bonjour,

il n'y aura normalement aucun probleme. Un système de migration est en place pour passer d'une version à une autre. Par ailleurs, La structure de Formcreator n'a pas beaucoup changer entre les version 0.84-2.X et 0.85-1.X de GLPI.

La procédure est la même que n'importe quel plugin :
1. Remplacez les fichiers de GLPI
2. Remplacez les fichiers des plugins par ceux d'une version compatible avec la nouvelle version de GLPI (Dans le cas de Formcreator et GLPI 0.85, la version 0.85-1.2.1).
3. Suivez les instructions de migration de GLPI
4. Effectuez la mise à jour des plugins depuis la page Configuration > Plugins de GLPI

Toutefois, par mesure de sécurité et comme toute migration de ce type, je vous encourage a : 
- Sauvegarder votre base de données et vos fichiers
- Créer si possible une copie de votre GLPI de production
- Testez la migration sur cet environnement de test avant de le faire sur votre prod.

Il est toutefois possible que vous rencontriez quelques soucis d'accents sur la future version. Nous prévoyons d'ici peu d'améliorer le script de migration pour régler ces soucis. En attendent, il suffit de ce rendre sur la configuration des questions posant problème et de les ré-enregistrer.

Bonne migration !

Cordialement,
Jérémy.

**Comment by matth974** [comment]
Bonjour,

Merci pour toute ces précisions.

Cordialement.
