### ISSUE TITLE
Copie de formulaire

### ISSUE THREAD

**Issue by MacDevil** [TECLIB/formcreator#90]
Bonjour,

Est-il possible de copier un formulaire ?

Si non est-il possible d'étudier la possibilité ?

Cordialement

**Comment by neeftarah** [comment]
Bonjour,

Cette fonctionnalité est déjà présente dans la version de formcreator pour GLPI 0.85 via les actions massives.
1. Dans la configuration des formulaires, sélectionnez vos formulaire à dupliquer.
2. Cliquez sur le bouton "Action".
3. Cliquez sur "Dupliquer".

Un backport de cette fonctionnalité pour la version 0.84 n'est pas du tout prévu, mais reste possible.

Cordialement,

**Comment by MacDevil** [comment]
Merci pour la réponse rapide !
