### ISSUE TITLE
Bug with encoding

### ISSUE THREAD

**Issue by consolko** [TECLIB/formcreator#91]
Hello. There is a problem when using like "checkbox" with the encoding in Russian. At input of the text in standard value, everything remains normally. On a form the same is displayed in the normal encoding. And here at preservation of the filled form, data from "checkbox" register in base crookedly. And in the demand are respectively displayed not correctly.
![text_in_form](https://cloud.githubusercontent.com/assets/9745539/6847183/9a5bacbe-d3d5-11e4-871e-c9af4e49b132.png)
![question_edit](https://cloud.githubusercontent.com/assets/9745539/6847181/9a59eeec-d3d5-11e4-812a-bc9a2373f600.png)
![save_form](https://cloud.githubusercontent.com/assets/9745539/6847182/9a5b3f90-d3d5-11e4-8e10-a9698e0ad75b.png)

**Comment by neeftarah** [comment]
Hi,
The problem is solved and the correction will be include in next release...
__But you need to have at least PHP 5.4 or greater to make it work.__

Thanks for your feedbak.
