### ISSUE TITLE
Bug Affichage du champ

### ISSUE THREAD

**Issue by fire2418** [TECLIB/formcreator#92]
Bonjour, 

J'ai remarqué un bug concernant l'affichage du champ, sur la dernière version de formcreator, 2.1.4 pour GLPI, version 0.847.

Lorsque je crée un formulaire normal, à une section, je peux faire s'afficher certaines questions en fonction de la réponse précédente.
Lorsque je rajoute une deuxième section avec des questions sans "critères" pour l'affichage des champs, tout fonctionne bien.
Lorsque j'ajoute des critères d'affichages sur les questions de la deuxième section, les critères sont respectés pour la deuxième section, mais plus pour la première section.

Pour résumer j'ai:
Section 1
Q1 question a choix multiple
Q2 critère sur la réponse de la question 1  section 1pour l'affichage d'une question en rapport avec le choix
Q3 critère sur la réponse de la question 1  section 1 pour l'affichage d'une question en rapport avec le choix

Section 2
Q1 question a choix multiple
Q2 critère sur la réponse de la question 1  section 2 pour l'affichage d'une question en rapport avec le choix
Q3 critère sur la réponse de la question 1  section 2 pour l'affichage d'une question en rapport avec le choix

En mode débug, il n'y a pas la moindre info ou erreur. J'espère que c'est assez clair.
Merci par avance pour votre retour

**Comment by neeftarah** [comment]
Merci de votre retour. C'est effectivement un bug que nous n'avions jamais testé sur la version 0.84.

Fixed by c78cf28

**Comment by fire2418** [comment]
Merci beaucoup pour votre réactivité !:)
